apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: kind-router01
    meta.helm.sh/release-namespace: ziti
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kind-router01-hook-serviceaccount
  namespace: ziti
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-scc-tc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: kind-router01-hook-serviceaccount
    namespace: ziti
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kind-router01
    app.kubernetes.io/part-of: kind-router01
    app.kubernetes.io/managed-by: kind-router01
  name: bpfd-app-rolebinding-kind-router01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-bpfprogram-viewer-role
subjects:
  - kind: ServiceAccount
    name: kind-router01-hook-serviceaccount
    namespace: ziti