---
name: release

on:
  pull_request:
    types: [closed]

env:
  APP_NAME: 'zfw'
  MAINTAINER: 'r-caamano'
  DESC: 'An ebpf based statefull fw for openziti edge-routers and tunnelers.'

jobs: 
  build_release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
          
      - name: Install EBPF Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get upgrade -yqq
          sudo apt-get install -y jq gcc clang libc6-dev-i386 libbpfcc-dev libbpf-dev libjson-c-dev
          
      - name:  Compile Object file from Source
        run: |
          clang -g -O2 -Wall -Wextra -target bpf -c -o files/bin/zfw_tc_ingress.o src/zfw_tc_ingress.c
          clang -g -O2 -Wall -Wextra -target bpf -c -o files/bin/zfw_xdp_tun_ingress.o src/zfw_xdp_tun_ingress.c
          clang -g -O2 -Wall -Wextra -target bpf -c -o files/bin/zfw_tc_outbound_track.o src/zfw_tc_outbound_track.c
          clang -O2 -Wall -Wextra -o files/bin/zfw src/zfw.c
          gcc -o files/bin/zfw_tunnwrapper src/zfw_tunnel_wrapper.c -l json-c
      
      - name: Get version
        run: echo "version=`files/bin/zfw -V`" >> $GITHUB_ENV
        id: version
        
      - name: Deb Object File
        run: |
          mkdir -p .debpkg/opt/openziti/bin/user
          mkdir -p .debpkg/opt/openziti/etc
          mkdir -p .debpkg/etc
          mkdir -p .debpkg/usr/sbin
          cp -p files/bin/zfw_xdp_tun_ingress.o .debpkg/opt/openziti/bin/
          cp -p files/bin/zfw_tc_ingress.o .debpkg/opt/openziti/bin/
          cp -p files/bin/zfw_tunnwrapper .debpkg/opt/openziti/bin/
          cp -p files/bin/zfw_tc_outbound_track.o .debpkg/opt/openziti/bin/
          cp -p files/bin/zfw .debpkg/opt/openziti/bin/zfw
          cp -p files/scripts/start_ebpf.py .debpkg/opt/openziti/bin/
          cp -p files/scripts/set_xdp_redirect.py .debpkg/opt/openziti/bin/
          cp -p files/scripts/user_rules.sh .debpkg/opt/openziti/bin/user/
          cp -p files/json/ebpf_config.json.sample .debpkg/opt/openziti/etc
          chmod +x .debpkg/opt/openziti/bin/set_xdp_redirect.py
          chmod +x .debpkg/opt/openziti/bin/start_ebpf.py
          chmod +x .debpkg/opt/openziti/bin/user/user_rules.sh
          ln -s /opt/openziti/bin/zfw .debpkg/usr/sbin/zfw
      - uses: jiro4989/build-deb-action@v2
        with:
              package: ${{ env.APP_NAME }}
              package_root: .debpkg
              maintainer: ${{ env.MAINTAINER }}
              version: ${{ env.version }}
              arch: ${{ matrix.goarch }}
              desc: '${{ env.DESC }}'

      - name: Create release
        uses: actions/create-release@v1
        id: release
        with:
          draft: false
          prerelease: false
          release_name: v${{ env.version }}
          tag_name: v${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload a built artifact for release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.APP_NAME }}_${{ env.version }}_${{ matrix.goarch }}.deb
          asset_name: ${{ env.APP_NAME }}_${{ env.version }}_${{ matrix.goarch }}.deb
          asset_content_type: application/vnd.debian.binary-package
